#!groovy


stage 'Dev'
node {
    checkout scm
    build 'clean install'
	deploy 'spring-boot:start'
    
}
environment {
    PATH = "$PATH"
	WORKSPACE="$WORKSPACE"
  }

stage 'QA'
parallel(longerTests: {
    runTests(30)
}, quickerTests: {
    runTests(20)
})


stage name: 'Production', concurrency: 1

def build(args) {
    
    sh "mvn ${args} -f back-end/pom.xml"
}

def runTests(duration) {
    node {
        sh "sleep ${duration}"
        }
    }

def deploy(id) {
    sh "mvn ${args} -f back-end/socle-java-application/pom.xml"
}

def undeploy(id) {
    
}
