#!groovy


stage 'Dev'
node {
    checkout scm
    mvn ' clean install '
    
}
environment {
    PATH = "$PATH"
	WORKSPACE="$WORKSPACE"
	WORKSPACE=WORKSPACE.trim()
  }

stage 'QA'
parallel(longerTests: {
    runTests(30)
}, quickerTests: {
    runTests(20)
})


stage name: 'Production', concurrency: 1

def mvn(args) {
    sh 'echo path= $WORKSPACE'
    sh 'mvn -f C:\ProgramFiles(x86)\Jenkins\workspace\socleJavaPipelinedev_master-DEK2AHBKCJP6VRO2K4VID3MCJVSJAMKS627NWEE5NNS7GEKEJRHQ\back-end\pom.xml  ${args}'
}

def runTests(duration) {
    node {
        sh "sleep ${duration}"
        }
    }

def deploy(id) {

}

def undeploy(id) {
    
}
